name: Test Build Merge Deploy

on:
  pull_request_target:
  push:
    branches: [main]

jobs:
  build-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Branch name
        run: echo running on branch ${{ github.event.pull_request.head.ref }}

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-python@v4.4.0
      - uses: pre-commit/action@v3.0.0

  pr-approve:
    runs-on: ubuntu-latest
    needs:
      - pre-commit
    steps:
      - uses: hmarr/auto-approve-action@v3.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  label-pr:
    runs-on: ubuntu-latest
    needs:
      - pr-approve
    steps:
      - uses: christianvuerings/add-labels@v1.1
        with:
          labels: |
            automerge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    runs-on: ubuntu-latest
    needs:
      - label-pr
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
